student: main.o header.o stud_add.o stud_show.o stud_save.o
	cc main.c header.c stud_add.c stud_show.c stud_save.c -o student

main.o: main.c
	cc -c main.c

header.o: header.c
	cc -c header.c

stud_add.o: stud_add.c
	cc -c stud_add.c

stud_show.o: stud_show.c
	cc -c stud_show.c 

stud_save.o: stud_save.c
	cc -c stud_save.c
